# Generated by Django 2.2.6 on 2019-11-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='', upload_to='ecom/images'),
        ),
    ]
