# Generated by Django 2.2.6 on 2019-11-19 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
