# Generated by Django 2.2.6 on 2019-11-30 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_auto_20191119_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('prod_json', models.CharField(max_length=500)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.Customer')),
            ],
        ),
    ]
