# Generated by Django 2.2.6 on 2019-11-30 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
