# Generated by Django 2.2.6 on 2019-11-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_order_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prods',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
