# Generated by Django 2.2.6 on 2019-11-20 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
